all:
  vars:
    ansible_password: vagrant
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ../ssh/id_rsa
  hosts:
    master-1:
      ansible_host: 192.168.60.11
    worker-1:
      ansible_host: 192.168.60.12
    worker-2:
      ansible_host: 192.168.60.13
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        master-1:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
        worker-1:
        worker-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: